name: A4091 software CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: stefanreinauer/amiga-gcc

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build a4091.device
      run: make a4091.device

    - name: Build a4091.rom
      run: make a4091.rom

    - name: Build a4091 tool
      run: make a4091

    - name: Build a4091d tool
      run: make a4091d

    - name: Build LHA archive
      run: make lha

    - name: Build ADF disk image
      run: cd disk && make

    - name: Archive CI artifacts (ROM)
      uses: actions/upload-artifact@v3
      with:
          name: Driver (AutoBoot ROM)
          path: ${{ github.workspace }}/a4091*.rom

    - name: Archive CI artifacts (LHA)
      uses: actions/upload-artifact@v3
      with:
          name: Driver (LHA)
          path: ${{ github.workspace }}/a4091_??.??.lha

    - name: Archive CI artifacts (ADF)
      uses: actions/upload-artifact@v3
      with:
          name: Disk Image (ADF)
          path: ${{ github.workspace }}/disk/A4091_????.adf

